InventoryManager/urls.py
from django.contrib import admin
from django.urls import path, include

from inventory_manager.views.add import add
from inventory_manager.views.qrcode import qrcode

from inventory_manager.views.allqrcode import allqrcode
from inventory_manager.views.scan import scan
from inventory_manager.views.index import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('scan', scan, name='scan'),
    path('allqrcode', allqrcode, name='allqrcode'),
    path('add', add, name='add'),
    path('qrcode/<slug:uidb64>/', qrcode, name='qrcode'),
]

inventory_manager/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Amovible(models.Model):
    uuid = models.OneToOneField('Objects', models.DO_NOTHING, db_column='uuid', primary_key=True)
    capacity = models.CharField(max_length=36, blank=True, null=True)
    tech = models.CharField(max_length=36, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'amovible'

    def __str__(self):
        return '{} {} | {}'.format(self.capacity, self.tech, self.uuid)


class Cable(models.Model):
    uuid = models.OneToOneField('Objects', models.DO_NOTHING, db_column='uuid', primary_key=True)
    length = models.CharField(max_length=36, blank=True, null=True)
    start_type = models.CharField(max_length=36, blank=True, null=True)
    end_type = models.CharField(max_length=36, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'cable'

    def __str__(self):
        return '{} | {}/{} | {}'.format(self.length, self.start_type, self.end_type, self.uuid)


class Cpu(models.Model):
    uuid = models.OneToOneField('Objects', models.DO_NOTHING, db_column='uuid', primary_key=True)
    core = models.IntegerField(blank=True, null=True)
    threads = models.IntegerField(blank=True, null=True)
    frequency = models.CharField(max_length=36, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'cpu'

    def __str__(self):
        return '{} | {}/{} | {}'.format(self.frequency, self.core, self.threads, self.uuid)

class Drive(models.Model):
    uuid = models.OneToOneField('Objects', models.DO_NOTHING, db_column='uuid', primary_key=True)
    capacity = models.CharField(max_length=36, blank=True, null=True)
    read_value = models.CharField(max_length=36, blank=True, null=True)
    write_value = models.CharField(max_length=36, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'drive'

    def __str__(self):
        return '{} | {}/{} | {}'.format(self.capacity, self.read_value, self.write_value, self.uuid)

class Hdd(models.Model):
    uuid = models.OneToOneField(Drive, models.DO_NOTHING, db_column='uuid', primary_key=True)
    rotation_speed = models.CharField(max_length=36, blank=True, null=True)
    size = models.CharField(max_length=36, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'hdd'

    def __str__(self):
        return '{} | {} | {}'.format(self.size, self.rotation_speed, self.uuid)


class Historic(models.Model):
    uuid = models.ForeignKey('Objects', models.DO_NOTHING, db_column='uuid')
    date = models.DateTimeField(blank=True, null=True)
    old_status = models.CharField(max_length=36, blank=True, null=True)
    new_status = models.CharField(max_length=36, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'historic'


class Objects(models.Model):
    uuid = models.CharField(primary_key=True, max_length=36)
    brand = models.CharField(max_length=36, blank=True, null=True)
    reference = models.CharField(max_length=36, blank=True, null=True)
    serial_number = models.CharField(max_length=36, blank=True, null=True)
    available = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'objects'

    def __str__(self):
        return '{} {} | {}'.format(self.brand, self.reference, "True" if self.available == 1 else "False")

class Ram(models.Model):
    uuid = models.OneToOneField(Objects, models.DO_NOTHING, db_column='uuid', primary_key=True)
    capacity = models.CharField(max_length=36, blank=True, null=True)
    type = models.CharField(max_length=36, blank=True, null=True)
    frequency = models.CharField(max_length=36, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ram'

    def __str__(self):
        return '{} | {}/{} | {}'.format(self.capacity, self.type, self.frequency, self.uuid)

class Smart(models.Model):
    startup_number = models.CharField(max_length=36, blank=True, null=True)
    power_count = models.CharField(max_length=36, blank=True, null=True)
    power_hours = models.CharField(max_length=36, blank=True, null=True)
    health_status = models.CharField(max_length=36, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'smart'


class SmartHdd(models.Model):
    id = models.OneToOneField(Smart, models.DO_NOTHING, db_column='id', primary_key=True)
    faulty_sector = models.CharField(max_length=36, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'smart_hdd'


class SmartSsd(models.Model):
    id = models.OneToOneField(Smart, models.DO_NOTHING, db_column='id', primary_key=True)
    total_read = models.CharField(max_length=36, blank=True, null=True)
    total_write = models.CharField(max_length=36, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'smart_ssd'


class Ssd(models.Model):
    uuid = models.OneToOneField(Drive, models.DO_NOTHING, db_column='uuid', primary_key=True)

    class Meta:
        managed = False
        db_table = 'ssd'

    def __str__(self):
        return '{}'.format(self.uuid)

inventory_manager/forms/amovibleForm.py
from django import forms


class AmovibleForm(forms.Form):
    capacity = forms.CharField()
    tech = forms.CharField()

    capacity.widget.attrs.update({'class': 'form-control'})
    tech.widget.attrs.update({'class': 'form-control'})

inventory_manager/forms/cableForm.py
from django import forms


class CableForm(forms.Form):
    length = forms.CharField()
    start_type = forms.CharField()
    end_type = forms.CharField()

    length.widget.attrs.update({'class': 'form-control'})
    start_type.widget.attrs.update({'class': 'form-control'})
    end_type.widget.attrs.update({'class': 'form-control'})

inventory_manager/forms/cpuForm.py
from django import forms


class CpuForm(forms.Form):
    core = forms.IntegerField()
    threads = forms.IntegerField()
    frequency = forms.CharField()

    core.widget.attrs.update({'class': 'form-control'})
    threads.widget.attrs.update({'class': 'form-control'})
    frequency.widget.attrs.update({'class': 'form-control'})

inventory_manager/forms/driveForm.py
from django import forms


class DriveForm(forms.Form):
    capacity = forms.CharField()
    read_value = forms.CharField()
    write_value = forms.CharField()

    capacity.widget.attrs.update({'class': 'form-control'})
    read_value.widget.attrs.update({'class': 'form-control'})
    write_value.widget.attrs.update({'class': 'form-control'})

inventory_manager/forms/hddForm.py
from django import forms


class HddForm(forms.Form):
    rotation_speed = forms.CharField(label='Rotation Speed')
    size = forms.CharField(label='Size')

    rotation_speed.widget.attrs.update({'class': 'form-control'})
    size.widget.attrs.update({'class': 'form-control'})

inventory_manager/forms/objectsForm.py
from django import forms


class ObjectsForm(forms.Form):
    brand = forms.CharField()
    reference = forms.CharField()
    serial_number = forms.CharField()
    available = forms.BooleanField()

    brand.widget.attrs.update({'class': 'form-control'})
    reference.widget.attrs.update({'class': 'form-control'})
    serial_number.widget.attrs.update({'class': 'form-control'})
    available.widget.attrs.update({'class': 'form-check-input', 'checked': 'checked', 'value': '1'})

inventory_manager/forms/ramForm.py
from django import forms


class RamForm(forms.Form):
    capacity = forms.CharField()
    type = forms.CharField()
    frequency = forms.CharField()

    capacity.widget.attrs.update({'class': 'form-control'})
    type.widget.attrs.update({'class': 'form-control'})
    frequency.widget.attrs.update({'class': 'form-control'})

inventory_manager/forms/ssdForm.py
from django import forms

inventory_manager/views/add.py
import uuid as uuid

from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from inventory_manager.forms.amovibleForm import AmovibleForm
from inventory_manager.forms.cableForm import CableForm
from inventory_manager.forms.cpuForm import CpuForm
from inventory_manager.forms.driveForm import DriveForm
from inventory_manager.forms.hddForm import HddForm
from inventory_manager.forms.objectsForm import ObjectsForm
from inventory_manager.forms.ramForm import RamForm
from inventory_manager.models import Objects, Amovible, Cable, Cpu, Ram, Drive, Hdd, Ssd


@login_required(login_url='/admin/login?next=/')
def add(request):
    if request.method == "POST":
        post = request.POST
        my_uuid = uuid.uuid4()
        available = 1 if 'available' in post else 0

        Objects(uuid=my_uuid, brand=post['brand'], reference=post['reference'], serial_number=post['serial_number'], available=available).save()
        obj = Objects.objects.all().filter(uuid=my_uuid).first()

        match post['selector'].lower():
            case 'amovible':
                Amovible(uuid=obj, capacity=post['capacity'], tech=post['tech']).save()
            case 'cable':
                Cable(uuid=obj, length=post['length'], start_type=post['start_type'], end_type=post['end_type']).save()
            case 'cpu':
                Cpu(uuid=obj, core=post['core'], threads=post['threads'], frequency=post['frequency']).save()
            case 'ram':
                Ram(uuid=obj, capacity=post['capacity'], type=post['type'], frequency=post['frequency']).save()
            case 'hdd':
                Drive(uuid=obj, capacity=post['capacity'], read_value=post['read_value'], write_value=post['write_value']).save()
                drive = Drive.objects.all().filter(uuid=my_uuid).first()
                Hdd(uuid=drive, rotation_speed=post['rotation_speed'], size=post['size']).save()
            case 'ssd':
                Drive(uuid=obj, capacity=post['capacity'], read_value=post['read_value'], write_value=post['write_value']).save()
                drive = Drive.objects.all().filter(uuid=my_uuid).first()
                Ssd(uuid=drive).save()

    objects_form = ObjectsForm()
    amovible_form = AmovibleForm()
    cable_form = CableForm()
    cpu_form = CpuForm()
    drive_form = DriveForm()
    hdd_form = HddForm()
    ram_form = RamForm()
    return render(request, 'add.html', {'objects': objects_form, 'amovible': amovible_form, 'cable': cable_form, 'cpu': cpu_form, 'drive': drive_form, 'hdd': hdd_form, 'ram': ram_form})

inventory_manager/views/allqrcode.py
import json

from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from inventory_manager.models import Objects


@login_required(login_url='/admin/login?next=/')
def allqrcode(request):
    objects = Objects.objects.all().order_by('-available')
    uuid = []
    brand = []
    reference = []
    serial_number = []

    for obj in objects:
        uuid.append(obj.uuid)
        brand.append(obj.brand)
        reference.append(obj.reference)
        serial_number.append(obj.serial_number)

    return render(request, 'allqrcode.html', {'uuid': uuid, 'brand': brand, 'reference': reference, 'serial_number': serial_number})

inventory_manager/views/index.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from inventory_manager.models import Objects, Ram, Cpu, Hdd, Ssd, Amovible, Cable


@login_required(login_url='/admin/login?next=/')
def index(request):
    #Variables
    objects = Objects.objects.all().order_by('-available')
    cpu = Cpu.objects.all().order_by('-uuid__available')
    ram = Ram.objects.all().order_by('-uuid__available')
    hdd = Hdd.objects.all().order_by('-uuid__uuid__available')
    ssd = Ssd.objects.all().order_by('-uuid__uuid__available')
    amovible = Amovible.objects.all().order_by('-uuid__available')
    cable = Cable.objects.all().order_by('-uuid__available')

    return render(request, 'index.html', {'objects': objects, 'cpu': cpu, 'ram': ram, 'hdd': hdd, 'ssd': ssd, 'amovible':
                                           amovible, 'cable': cable})

inventory_manager/views/qrcode.py
import objects
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect

from inventory_manager.models import Objects


@login_required(login_url='/admin/login?next=/')
def qrcode(request, uidb64):
    objects = Objects.objects.all().filter(uuid=uidb64).first()
    objects.available = not objects.available
    objects.save()
    return redirect('index')

inventory_manager/views/scan.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required(login_url='/admin/login?next=/')
def scan(request):
    return render(request, 'scan.html', {})

inventory_manager/templates/add.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add{% endblock %}
{% block content %}
    <div class="min-vh-100">
        <script src="{% static 'js/formManager.js' %}" type="text/javascript" defer></script>
        <form style="margin-top: 32px;" id="object-form" method="post">
            {% csrf_token %}
            <h1 style="margin-left: 32px;font-size: 48px;">Object Creation</h1>
            <div class="container" style="margin-top: 16px;">
                <div class="row">
                    <div class="col-md-3"><label for="id_brand" class="form-label">Brand</label>{{ objects.brand }}
                    </div>
                    <div class="col-md-3"><label for="id_reference"
                                                 class="form-label">Reference</label>{{ objects.reference }}</div>
                    <div class="col-md-3"><label for="id_serial_number" class="form-label">Serial
                        Number</label>{{ objects.serial_number }}</div>
                    <div class="col-md-3">
                        <div class="form-check"><label class="form-check-label" for="id_available">Available</label>
                            {{ objects.available }}
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <div class="container" style="margin-top: 32px;">
            <form id="selector-form" method="post">
                <select style="margin-top: 16px;" id="selector" name="selector">
                    <option value="amovible">Amovible</option>
                    <option value="cable">Cable</option>
                    <option value="cpu">Cpu</option>
                    <option value="ram">Ram</option>
                    <option value="hdd">Hdd</option>
                    <option value="ssd">Ssd</option>
                </select>
            </form>
        </div>
        <form style="margin-top: 32px;" id="amovible-form" method="post">
            <h1 style="margin-left: 32px;font-size: 48px;">Amovible</h1>
            <div class="container" style="margin-top: 16px;">
                <div class="row">
                    <div class="col-md-3"><label for="id_capacity"
                                                 class="form-label">Capacity</label> {{ amovible.capacity }}</div>
                    <div class="col-md-3"><label for="id_tech" class="form-label">Tech</label> {{ amovible.tech }}</div>
                </div>
            </div>
        </form>
        <form style="margin-top: 32px;" id="cable-form" method="post">
            <h1 style="margin-left: 32px;font-size: 48px;">Cable</h1>
            <div class="container" style="margin-top: 16px;">
                <div class="row">
                    <div class="col-md-3"><label for="id_length" class="form-label">Length</label>{{ cable.length }}
                    </div>
                    <div class="col-md-3"><label for="id_start_type" class="form-label">Start
                        type</label>{{ cable.start_type }}</div>
                    <div class="col-md-3"><label for="id_end_type" class="form-label">End
                        type</label>{{ cable.end_type }}</div>
                </div>
            </div>
        </form>
        <form style="margin-top: 32px;" id="cpu-form" method="post">
            <h1 style="margin-left: 32px;font-size: 48px;">Cpu</h1>
            <div class="container" style="margin-top: 16px;">
                <div class="row">
                    <div class="col-md-3"><label for="id_core" class="form-label">Core number</label>{{ cpu.core }}
                    </div>
                    <div class="col-md-3"><label for="id_threads" class="form-label">Thread
                        number</label>{{ cpu.threads }}</div>
                    <div class="col-md-3"><label for="id_frequency"
                                                 class="form-label">Frequency</label>{{ cpu.frequency }}</div>
                </div>
            </div>
        </form>
        <form style="margin-top: 32px;" id="ram-form" method="post">
            <h1 style="margin-left: 32px;font-size: 48px;">Ram</h1>
            <div class="container" style="margin-top: 16px;">
                <div class="row">
                    <div class="col-md-3"><label for="id_capacity" class="form-label">Capacity</label>{{ ram.capacity }}
                    </div>
                    <div class="col-md-3"><label for="id_type" class="form-label">Type</label>{{ ram.type }}</div>
                    <div class="col-md-3"><label for="id_frequency"
                                                 class="form-label">Frequency</label>{{ ram.frequency }}</div>
                </div>
            </div>
        </form>
        <form style="margin-top: 32px;" id="drive-form" method="post">
            <h1 style="margin-left: 32px;font-size: 48px;">Drive</h1>
            <div class="container" style="margin-top: 16px;">
                <div class="row">
                    <div class="col-md-3"><label for="id_capacity"
                                                 class="form-label">Capacity</label>{{ drive.capacity }}</div>
                    <div class="col-md-3"><label for="id_read_value" class="form-label">Read
                        speed</label>{{ drive.read_value }}</div>
                    <div class="col-md-3"><label for="id_write_value" class="form-label">Write
                        speed</label>{{ drive.write_value }}</div>
                </div>
            </div>
        </form>
        <form style="margin-top: 32px;" id="hdd-form" method="post">
            <h1 style="margin-left: 32px;font-size: 48px;">Hdd</h1>
            <div class="container" style="margin-top: 16px;">
                <div class="row">
                    <div class="col-md-3"><label for="id_rotation_speed" class="form-label">Rotation
                        speed</label>{{ hdd.rotation_speed }}</div>
                    <div class="col-md-3"><label for="id_size" class="form-label">Format factor</label>{{ hdd.size }}
                    </div>
                </div>
            </div>
        </form>
        <form style="margin-top: 32px;" id="ssd-form" method="post">
            <h1 style="margin-left: 32px;font-size: 48px;">Ssd</h1>
            <div class="container" style="margin-top: 16px;">
                <div class="row">
                    <div class="col-md-3"><label for="id_" class="form-label"></label></div>
                    <div class="col-md-3"><label for="id_" class="form-label"></label></div>
                    <div class="col-md-3"><label for="id_" class="form-label"></label></div>
                    <div class="col-md-3"><label for="id_" class="form-label"></label></div>
                </div>
            </div>
        </form>
        <button style="margin-left: 32px; margin-top: 32px;" class="btn btn-primary" type="button"
                onclick="submitForms()">Send data
        </button>
    </div>
{% endblock %}

inventory_manager/templates/allqrcode.html
{% extends 'base.html' %}
{% load static %}
{% block title %}AllQrcode{% endblock %}
{% block content %}

    <div class="min-vh-100">
        <button type="button" class="btn btn-primary mt-4 mb-2" style="margin: 32px;" onclick="printAllQrcode();">Print Qrcode</button>
        <section id="display"></section>
        <input type="hidden" id="uuid" value="{{ uuid }}">
        <input type="hidden" id="brand" value="{{ brand }}">
        <input type="hidden" id="reference" value="{{ reference }}">
        <input type="hidden" id="serial" value="{{ serial_number }}">
        <script src="https://cdn.jsdelivr.net/gh/davidshimjs/qrcodejs/qrcode.min.js"></script>
        <script src="{% static 'js/allqrcode.js' %}" type="text/javascript"> </script>
        <style>
            #display {
                margin-left: 32px;
                margin-right: 32px;
                display: grid;
                grid-template-columns: repeat(4, 1fr);
                grid-gap: 10px;
            }
        </style>
    </div>
{% endblock %}

inventory_manager/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<link rel="manifest" href="{% static 'manifest.json' %}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Inventory Manager</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&amp;display=swap">
    <link rel="stylesheet" href="{% static 'css/Navbar-Right-Links-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/shadow.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

</head>
<body>
<header>
    <nav class="navbar navbar-dark navbar-expand-md bg-dark py-3">
        <div class="container"><a class="navbar-brand d-flex align-items-center" href="{% url 'index' %}"><span
                class="bs-icon-sm bs-icon-rounded bs-icon-primary d-flex justify-content-center align-items-center me-2 bs-icon"><svg
                xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16"
                class="bi bi-box-seam">
                        <path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5l2.404.961L10.404 2l-2.218-.887zm3.564 1.426L5.596 5 8 5.961 14.154 3.5l-2.404-.961zm3.25 1.7-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464L7.443.184z"></path>
                    </svg></span><span>Inventory Manger V1</span></a>
            <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-5"><span
                    class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-5">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="https://home.enzo-laurence.tech">Home</a></li>
                    <li class="nav-item"><a class="nav-link active" href="{% url 'index' %}">Index</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'allqrcode' %}">All QR Code</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                    {% if request.user.is_authenticated == False %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'admin:login' %}?next={% url 'index' %}">Login</a></li>
                    {% else%}
                        <li class="nav-item"><a class="nav-link" href="{% url 'admin:logout' %}?next={% url 'index' %}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<main>
    {% block content %}
    {% endblock %}
</main>
<footer>
    <div class="fixed-bottom" style="margin-bottom: 16px;">
        <div class="btn-group float-xl-end" role="group">
            <a href="{% url 'scan' %}">
                <button class="btn btn-primary" type="button"
                        style="margin-right: 8px;border-radius: 50%;width: 64px;height: 64px;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                         viewBox="0 0 16 16"
                         class="bi bi-qr-code-scan" style="width: 32px;height: 32px;">
                        <path fill-rule="evenodd"
                              d="M0 .5A.5.5 0 0 1 .5 0h3a.5.5 0 0 1 0 1H1v2.5a.5.5 0 0 1-1 0v-3Zm12 0a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0V1h-2.5a.5.5 0 0 1-.5-.5ZM.5 12a.5.5 0 0 1 .5.5V15h2.5a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5v-3a.5.5 0 0 1 .5-.5Zm15 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1 0-1H15v-2.5a.5.5 0 0 1 .5-.5ZM3 3h3v3H3V3Zm0 7h3v3H3v-3Zm7-7h3v3h-3V3ZM7 2H2v5h5V2Zm0 7H2v5h5V9Zm2-7h5v5H9V2ZM4 4h1v1H4V4Zm7 0h1v1h-1V4Zm-6 7H4v1h1v-1Zm3.5-3H8v2h1v1H8v1h2v-2h1v2h1v-1h2v-1h-3V8H8.5Zm1.5 2V9H9v1h1Zm4 3.5V12h-1v1h-2v1h3v-.5Zm-4 .5v-1H8v1h2Zm2-5h2V8h-2v1Z"></path>
                    </svg>
                </button>
            </a>
            <a href="{% url 'add' %}">
                <button class="btn btn-primary" type="button"
                        style="margin-right: 8px;border-radius: 50%;width: 64px;height: 64px;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                         viewBox="0 0 16 16"
                         class="bi bi-plus" style="width: 32px;height: 32px;">
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"></path>
                    </svg>
                </button>
            </a>
            {% block flashlight %}{% endblock %}
        </div>
    </div>
</footer>
</body>
</html>

inventory_manager/templates/scan.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}
    <div class="min-vh-100">
        <div id="reader" width="600px" height="600px"></div>
        <script src="https://unpkg.com/html5-qrcode" type="text/javascript"> </script>
        <script src="{% static 'js/scanner.js' %}" type="text/javascript"> </script>
        <script src="{% static 'js/flashlight.js' %}" type="text/javascript"> </script>
    </div>
{% endblock %}
{% block flashlight %}
    <button class="btn btn-primary switch" type="button" style="margin-right: 8px;border-radius: 50%;width: 64px;height: 64px;">
        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-lightbulb" style="width: 32px;height: 32px;">
            <path d="M2 6a6 6 0 1 1 10.174 4.31c-.203.196-.359.4-.453.619l-.762 1.769A.5.5 0 0 1 10.5 13a.5.5 0 0 1 0 1 .5.5 0 0 1 0 1l-.224.447a1 1 0 0 1-.894.553H6.618a1 1 0 0 1-.894-.553L5.5 15a.5.5 0 0 1 0-1 .5.5 0 0 1 0-1 .5.5 0 0 1-.46-.302l-.761-1.77a1.964 1.964 0 0 0-.453-.618A5.984 5.984 0 0 1 2 6zm6-5a5 5 0 0 0-3.479 8.592c.263.254.514.564.676.941L5.83 12h4.342l.632-1.467c.162-.377.413-.687.676-.941A5 5 0 0 0 8 1z"></path>
        </svg>
    </button>
{% endblock %}